/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/end/': RouteRecordInfo<'/end/', '/end', Record<never, never>, Record<never, never>>,
    '/final_question/': RouteRecordInfo<'/final_question/', '/final_question', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/question/': RouteRecordInfo<'/question/', '/question', Record<never, never>, Record<never, never>>,
    '/work/': RouteRecordInfo<'/work/', '/work', Record<never, never>, Record<never, never>>,
  }
}
